apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-deployment
  labels:
    app: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
        - name: demo
          image: nizam333/learning-repo:demoapp
          ports:
            - containerPort: 8080
---

#apiVersion: v1
#kind: Service
#metadata:
#  name: demo-deployment
#spec:
#  type: NodePort
#  selector:
#    app: demo
#  ports:
#    - protocol: TCP
#      port: 8080
#      targetPort: 8080
#      nodePort: 30000